language: node_js
node_js: stable

branches:
  only:
    - hexo  # 设置自动化部署的源码分支

# cache this directory
cache:
  directories:
    - node_modules
    #- themes 主题没有更改时可以缓存

before_install:
- export TZ='Asia/Shanghai'  # 设置时区
- npm install -g hexo
- npm install -g hexo-cli

# 安装依赖组件
install:
  - npm install

# 执行的命令
script:
  - hexo generate

after_success:
  # 设置github账户信息
  - git config --global user.name "wangchi" #设置github用户名
  - git config --global user.email wangchi1995@gmail.com #设置github用户邮箱
  - sed -i "s/git@/${CI_TOKEN}@/g" _config.yml #使用travisCI中配置的token替换掉_config.yml中对应的占位符
  - hexo deploy